AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: techchallenge-feedback

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java21
    LoggingConfig:
      LogFormat: JSON

Resources:

  FeedbacksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FeedbacksTable
      AttributeDefinitions:
        - AttributeName: feedbackId
          AttributeType: S
      KeySchema:
        - AttributeName: feedbackId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE
    Metadata:
      SamResourceId: FeedbacksTable

  FeedbackDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: FeedbackDLQ
    Metadata:
      SamResourceId: FeedbackDLQ

  IngestFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ingest-feedback
      CodeUri: ./ingest-feedback
      Handler: lambda.IngestFeedbackFunction::handleRequest
      Runtime: java21
      Events:
        Api:
          Type: Api
          Properties:
            Path: /feedback
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: FeedbacksTable
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt FeedbackDLQ.Arn
    Metadata:
      SamResourceId: IngestFeedbackFunction

  SendQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: send-queue
      CodeUri: ./send-queue
      Handler: lambda.SendQueueFunction::handleRequest
      Runtime: java21
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt FeedbacksTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 5
      Policies:
        - DynamoDBReadPolicy:
            TableName: FeedbacksTable
        - SQSSendMessagePolicy:
            QueueName: FeedbackDLQ
        - Statement:
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt FeedbackDLQ.Arn
    Metadata:
      SamResourceId: SendQueueFunction

  NotifyCriticalFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: notify-critical
      CodeUri: ./notify-critical
      Handler: lambda.NotifyCriticalFunction::handleRequest
      Runtime: java21
      Policies:
        - SQSPollerPolicy:
            QueueName: FeedbackDLQ
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt FeedbackDLQ.Arn
    Metadata:
      SamResourceId: NotifyCriticalFunction

  CriticalFeedbackRule:
    Type: AWS::Events::Rule
    Properties:
      Name: CriticalFeedbackRule
      EventPattern:
        source:
          - feedback.created
        detail-type:
          - FeedbackCreated
        detail:
          isCritical:
            - true
      Targets:
        - Arn: !GetAtt NotifyCriticalFunction.Arn
          Id: NotifyCriticalFunctionTarget

Outputs:
  ApiUrl:
    Description: URL da API de feedback
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/feedback
  IngestFeedbackFunctionArn:
    Description: ARN da função ingest-feedback
    Value: !GetAtt IngestFeedbackFunction.Arn
  SendQueueFunctionArn:
    Description: ARN da função send-queue
    Value: !GetAtt SendQueueFunction.Arn
  NotifyCriticalFunctionArn:
    Description: ARN da função notify-critical
    Value: !GetAtt NotifyCriticalFunction.Arn