AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: techchallenge-feedback

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java21
    LoggingConfig:
      LogFormat: JSON

Resources:

  # DynamoDB para feedbacks
  FeedbacksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FeedbacksTable
      AttributeDefinitions:
        - AttributeName: feedbackId
          AttributeType: S
      KeySchema:
        - AttributeName: feedbackId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE
    Metadata:
      SamResourceId: FeedbacksTable

  # Dead Letter Queue
  FeedbackDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: FeedbackDLQ
    Metadata:
      SamResourceId: FeedbackDLQ

  # Função ingest-feedback exposta via API protegida por Cognito
  IngestFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ingest-feedback
      CodeUri: ./ingest-feedback
      Handler: lambda.IngestFeedbackFunction::handleRequest
      Runtime: java21
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /feedback
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: FeedbacksTable
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt FeedbackDLQ.Arn
    Metadata:
      SamResourceId: IngestFeedbackFunction

  SendQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: send-queue
      CodeUri: ./send-queue
      Handler: lambda.SendQueueFunction::handleRequest
      Runtime: java21
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt FeedbacksTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 5
      Policies:
        - DynamoDBReadPolicy:
            TableName: FeedbacksTable
        - SQSSendMessagePolicy:
            QueueName: FeedbackDLQ
        - Statement:
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt FeedbackDLQ.Arn
    Metadata:
      SamResourceId: SendQueueFunction

  NotifyCriticalFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: notify-critical
      CodeUri: ./notify-critical
      Handler: lambda.NotifyCriticalFunction::handleRequest
      Runtime: java21
      Policies:
        - SQSPollerPolicy:
            QueueName: FeedbackDLQ
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt FeedbackDLQ.Arn
    Metadata:
      SamResourceId: NotifyCriticalFunction

  CriticalFeedbackRule:
    Type: AWS::Events::Rule
    Properties:
      Name: CriticalFeedbackRule
      EventPattern:
        source:
          - feedback.created
        detail-type:
          - FeedbackCreated
        detail:
          isCritical:
            - true
      Targets:
        - Arn: !GetAtt NotifyCriticalFunction.Arn
          Id: NotifyCriticalFunctionTarget

  # Permissão para EventBridge invocar a Lambda notify-critical
  NotifyCriticalInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref NotifyCriticalFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CriticalFeedbackRule.Arn

  # Cognito User Pool
  MyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: FeedbackUserPool
      AutoVerifiedAttributes:
        - email

  # Google Identity Provider (usando Secrets Manager)
  GoogleIdP:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      ProviderName: Google
      ProviderType: Google
      UserPoolId: !Ref MyUserPool
      AttributeMapping:
        email: email
        given_name: given_name
        family_name: family_name
      ProviderDetails:
        client_id: "{{resolve:secretsmanager:GoogleOAuthCredentials:SecretString:client_id}}"
        client_secret: "{{resolve:secretsmanager:GoogleOAuthCredentials:SecretString:client_secret}}"
        authorize_scopes: "openid profile email"

  # Cognito User Pool Client
  MyUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: FeedbackAppClient
      UserPoolId: !Ref MyUserPool
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
        - Google
      CallbackURLs:
        - !Sub "https://${MyApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/feedback"
      LogoutURLs:
        - !Sub "https://${MyApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/logout"
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
    DependsOn: GoogleIdP

  # Cognito Hosted UI Domain
  MyUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: feedback-login
      UserPoolId: !Ref MyUserPool

  # API Gateway protegido com Cognito
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !GetAtt MyUserPool.Arn

Outputs:
  FeedbackApiUrl:
    Description: URL da API de feedback protegida por Cognito
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/feedback"

  IngestFeedbackFunctionArn:
    Description: ARN da função ingest-feedback
    Value: !GetAtt IngestFeedbackFunction.Arn

  SendQueueFunctionArn:
    Description: ARN da função send-queue
    Value: !GetAtt SendQueueFunction.Arn

  NotifyCriticalFunctionArn:
    Description: ARN da função notify-critical
    Value: !GetAtt NotifyCriticalFunction.Arn