AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: techchallenge-feedback

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java21
    LoggingConfig:
      LogFormat: JSON

Resources:

  # DynamoDB para feedbacks
  FeedbacksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FeedbacksTable
      AttributeDefinitions:
        - AttributeName: feedbackId
          AttributeType: S
        - AttributeName: pk
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: feedbackId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: pk-createdAt-index
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  # Dead Letter Queue
  FeedbackDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: FeedbackDLQ

  # Função insert-feedback exposta via API protegida por Cognito
  InsertFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: insert-feedback
      CodeUri: insert-feedback/target/insert-feedback-1.0.jar
      Handler: lambda.InsertFeedbackFunction::handleRequest
      Runtime: java21
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /feedback
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: FeedbacksTable
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt FeedbackDLQ.Arn

  SendQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: send-queue
      CodeUri: send-queue/target/send-queue-1.0.jar
      Handler: lambda.SendQueueFunction::handleRequest
      Runtime: java21
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt FeedbacksTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 5
      Policies:
        - DynamoDBReadPolicy:
            TableName: FeedbacksTable
        - SQSSendMessagePolicy:
            QueueName: FeedbackDLQ
        - Statement:
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt FeedbackDLQ.Arn

  NotifyCriticalFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: notify-critical
      CodeUri: notify-critical/target/notify-critical-1.0.jar
      Handler: lambda.NotifyCriticalFunction::handleRequest
      Runtime: java21
      Policies:
        - SQSPollerPolicy:
            QueueName: FeedbackDLQ
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt FeedbackDLQ.Arn

  CriticalFeedbackRule:
    Type: AWS::Events::Rule
    Properties:
      Name: CriticalFeedbackRule
      EventPattern:
        source:
          - feedback.created
        detail-type:
          - FeedbackCreated
        detail:
          isCritical:
            - true
      Targets:
        - Arn: !GetAtt NotifyCriticalFunction.Arn
          Id: NotifyCriticalFunctionTarget

  # Permissão para EventBridge invocar a Lambda notify-critical
  NotifyCriticalInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref NotifyCriticalFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CriticalFeedbackRule.Arn

  # === NOVAS LAMBDAS PARA RELATÓRIOS ===

  # S3 Bucket para relatórios semanais
  FeedbackReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "feedback-reports-${AWS::StackName}-${AWS::AccountId}"

  # Lambda para listar feedbacks
  ListFeedbacksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list-feedbacks
      CodeUri: list-feedbacks/target/list-feedbacks-1.0.jar
      Handler: lambda.ListFeedbacksFunction::handleRequest
      Runtime: java21
      Environment:
        Variables:
          TABLE_NAME: !Ref FeedbacksTable
          DEFAULT_PAGE_SIZE: 100
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /feedbacks
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FeedbacksTable
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt FeedbackDLQ.Arn

  # Lambda para gerar relatório semanal
  GenerateWeeklyReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: generate-weekly-report
      CodeUri: generate-weekly-report/target/generate-weekly-report-1.0.jar
      Handler: lambda.GenerateWeeklyReportFunction::handleRequest
      Runtime: java21
      Environment:
        Variables:
          REPORTS_BUCKET: !Ref FeedbackReportsBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref FeedbackReportsBucket
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt FeedbackDLQ.Arn

  # Lambda para notificar relatório via SES
  NotifyReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: notify-report
      CodeUri: notify-report/target/notify-report-1.0.jar
      Handler: lambda.NotifyReportFunction::handleRequest
      Runtime: java21
      Environment:
        Variables:
          REPORTS_BUCKET: !Ref FeedbackReportsBucket
          RECIPIENT_EMAIL: "luanacherri@gmail.com"
          SOURCE_EMAIL: "luanacherri@gmail.com"
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref FeedbackReportsBucket
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt FeedbackDLQ.Arn

  # Step Functions State Machine para processar feedbacks
  FeedbackProcessingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: feedback-processing
      DefinitionUri: statemachine/feedback-processing.asl.json
      DefinitionSubstitutions:
        ListFeedbacksFunctionArn: !GetAtt ListFeedbacksFunction.Arn
        GenerateWeeklyReportFunctionArn: !GetAtt GenerateWeeklyReportFunction.Arn
        NotifyReportFunctionArn: !GetAtt NotifyReportFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ListFeedbacksFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GenerateWeeklyReportFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifyReportFunction

  # EventBridge Rule para trigger semanal (domingo às 23:00 UTC)
  WeeklyReportScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: WeeklyReportSchedule
      Description: Trigger semanal para gerar relatório de feedbacks
      ScheduleExpression: cron(0 23 ? * SUN *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt FeedbackProcessingStateMachine.Arn
          Id: WeeklyReportTarget
          RoleArn: !GetAtt EventBridgeStateMachineRole.Arn
          Input: |
            {
              "startDate": "2020-01-01T00:00:00Z",
              "endDate": "2030-12-31T23:59:59Z"
            }

  # IAM Role para EventBridge invocar Step Functions
  EventBridgeStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StartStateMachinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !GetAtt FeedbackProcessingStateMachine.Arn

  # Cognito User Pool
  # API Gateway (sem autenticação)
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

Outputs:
  FeedbackApiUrl:
    Description: URL da API de feedback (sem autenticação)
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/feedback"

  InsertFeedbackFunctionArn:
    Description: ARN da função insert-feedback
    Value: !GetAtt InsertFeedbackFunction.Arn

  SendQueueFunctionArn:
    Description: ARN da função send-queue
    Value: !GetAtt SendQueueFunction.Arn

  NotifyCriticalFunctionArn:
    Description: ARN da função notify-critical
    Value: !GetAtt NotifyCriticalFunction.Arn

  ListFeedbacksFunctionArn:
    Description: ARN da função list-feedbacks
    Value: !GetAtt ListFeedbacksFunction.Arn

  GenerateWeeklyReportFunctionArn:
    Description: ARN da função generate-weekly-report
    Value: !GetAtt GenerateWeeklyReportFunction.Arn

  NotifyReportFunctionArn:
    Description: ARN da função notify-report
    Value: !GetAtt NotifyReportFunction.Arn

  FeedbackReportsBucketName:
    Description: Nome do bucket S3 para relatórios
    Value: !Ref FeedbackReportsBucket

  FeedbackProcessingStateMachineArn:
    Description: ARN da Step Function para processamento de feedbacks
    Value: !GetAtt FeedbackProcessingStateMachine.Arn

  ListFeedbacksApiUrl:
    Description: URL da API para listar feedbacks
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/feedbacks"
